# Generated by Django 5.1.1 on 2024-10-12 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('thread', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionthread',
            name='subject',
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
